"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Bookmark, CheckCircle2, Clock3, Layers, Plus, RefreshCw, ShieldCheck, Users } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { ProgressBar } from "@/components/ui/ProgressBar";
import { useAuth } from "@/lib/auth/AuthContext";
import { resourceTypeLabel } from "@/lib/client/catalog-api";
import { getAdminStats, getLearning, listAccessHistory, listBookmarks, listOwnSubmissions, listSubmissionsForReview, listPendingUsers } from "@/lib/client/workspace-api";
import { useDatabaseData } from "@/lib/client/use-database-data";
import { formatRelativeTime } from "@/lib/utils";

export default function DashboardPage() {
  const { user } = useAuth();
  return <AppShell title={user?.role === "admin" ? "Platform overview" : user?.role === "contributor" ? "Studio overview" : "My learning"}>
    {user?.role === "admin" ? <AdminDashboard /> : user?.role === "contributor" ? <ContributorDashboard /> : user ? <LearnerDashboard /> : null}
  </AppShell>;
}
function LearnerDashboard() {
  const { user } = useAuth();
  const key = user?.id ?? "anonymous";
  const learning = useDatabaseData(`dashboard-learning:${key}`, getLearning, { courses: [], topics: [] });
  const bookmarks = useDatabaseData(`dashboard-bookmarks:${key}`, listBookmarks, []);
  const access = useDatabaseData(`dashboard-access:${key}`, listAccessHistory, []);
  const next = learning.data.topics.find(topic => !topic.completed);
  const target = next ? `/courses/${next.courseId}/topics/${next.topicId}` : learning.data.courses[0] ? `/courses/${learning.data.courses[0].courseId}` : "/courses";
  return <div className="space-y-8">
    <section className="learning-hero"><div className="relative z-10"><p className="page-kicker mb-4">Your next chapter</p><h2>A little progress.<br />A world of possibility.</h2><p className="mt-5 max-w-md text-sm leading-6 text-slate-500">Welcome back, {user?.name.split(" ")[0]}. {next ? `Pick up where you left off with ${next.topicName}.` : "Find your course, follow its roadmap, and make today count."}</p><div className="mt-7 flex flex-wrap gap-3"><Link className="action-primary" href={target}>{next ? "Continue learning" : "Find your next lesson"}<ArrowRight size={16} /></Link><Link className="action-secondary" href="/courses">Explore courses</Link></div></div></section>
    {(learning.error || bookmarks.error || access.error) && <p role="alert" className="text-sm text-rose-600">{learning.error ?? bookmarks.error ?? access.error}</p>}
    <div className="grid gap-4 sm:grid-cols-3">{[{ label: "Courses in your library", value: learning.data.courses.length, href: "/progress", icon: BookOpen }, { label: "Topics completed", value: learning.data.topics.filter(topic => topic.completed).length, href: "/progress", icon: CheckCircle2 }, { label: "Resources saved", value: bookmarks.data.length, href: "/bookmarks", icon: Bookmark }].map(({ label, value, href, icon: Icon }) => <Link key={label} href={href} className="flex items-center gap-4 rounded-2xl border border-slate-200/70 bg-white p-5"><span className="rounded-xl bg-indigo-50 p-3 text-indigo-500"><Icon size={21} /></span><span><strong className="block text-2xl font-semibold">{learning.isLoading || bookmarks.isLoading ? "?" : value}</strong><span className="text-xs text-slate-500">{label}</span></span><ArrowUpRight className="ml-auto text-slate-300" size={16} /></Link>)}</div>
    <div className="grid gap-8 xl:grid-cols-[1fr_300px]"><section><div className="mb-5 flex items-center justify-between"><div><p className="page-kicker mb-2">Keep your momentum</p><h3 className="text-xl font-semibold tracking-tight">Your course library</h3></div><Link href="/progress" className="text-xs font-semibold text-indigo-600">View progress ?</Link></div><div className="grid gap-4 sm:grid-cols-2">{learning.data.courses.map((course, index) => <Link className="course-tile" key={course.enrollmentId} href={`/courses/${course.courseId}`}><div className="mb-5 flex items-center justify-between"><span className="rounded-lg bg-indigo-50 p-3 text-indigo-500"><BookOpen size={22} /></span><span className="font-mono text-xs text-slate-300">{String(index + 1).padStart(2, "0")}</span></div><span className="page-kicker">{course.code}</span><h4 className="mt-2 mb-5 text-base font-semibold">{course.name}</h4><ProgressBar percent={course.progressPercent} /><p className="mt-3 text-xs text-slate-500">{course.progressPercent}% complete <ArrowRight size={14} className="float-right" /></p></Link>)}</div>{!learning.isLoading && !learning.data.courses.length && <div className="rounded-2xl border border-dashed border-slate-300 p-8 text-sm text-slate-500">Your library starts with a course. <Link href="/courses" className="font-semibold text-indigo-600">Explore the catalog ?</Link></div>}{learning.isLoading && <p className="text-sm text-slate-400">Loading your courses?</p>}</section><aside className="panel h-fit"><div className="panel-heading"><h3>Recently opened</h3><Clock3 size={16} className="text-slate-400" /></div><div className="px-5">{access.data.slice(0, 5).map(entry => <Link key={entry.id} href={`/resources/${entry.resourceId}`} className="block border-b border-slate-100 py-4 last:border-0"><p className="text-xs text-indigo-500">{resourceTypeLabel(entry.resourceType)}</p><p className="mt-1 text-sm font-medium">{entry.resourceTitle}</p><p className="mt-2 text-[10px] text-slate-400">{formatRelativeTime(entry.accessedAt)}</p></Link>)}{!access.data.length && <p className="py-6 text-sm text-slate-400">Your reading history will appear here.</p>}</div><Link href="/access-history" className="block border-t border-slate-100 px-5 py-4 text-xs font-semibold text-indigo-600">All reading history ?</Link></aside></div>
  </div>;
}
function ContributorDashboard() {
  const { user } = useAuth();
  const result = useDatabaseData(`studio:${user?.id}`, listOwnSubmissions, []);
  return <div className="space-y-7"><section className="studio-banner"><div><p className="page-kicker mb-3">Contributor studio / {user?.name.split(" ")[0]}</p><h2 className="page-title max-w-lg text-4xl">Good knowledge<br />deserves to be shared.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-slate-600">A home for your notes, practice sets, and teaching materials. Follow each contribution from submission to publication.</p><Link href="/contributor/submissions" className="action-primary mt-6"><Plus size={16} />Create a submission</Link></div><div className="flex flex-col justify-center border-l border-emerald-900/10 pl-7"><span className="text-6xl font-light tracking-tighter text-emerald-900">{result.isLoading ? "?" : result.data.filter(row => row.status === "approved").length}</span><p className="mt-2 text-xs font-medium text-emerald-800">Approved contributions</p><Link href="/contributor/courses" className="mt-6 flex items-center gap-2 text-xs text-emerald-800">Your course workspace <ArrowUpRight size={14} /></Link></div></section>
    {result.error && <p role="alert" className="text-sm text-rose-600">{result.error}</p>}
    <div className="flex items-end justify-between"><div><p className="page-kicker mb-2">Your publishing desk</p><h3 className="text-xl font-semibold tracking-tight">Every contribution, in view.</h3></div><button onClick={result.refresh} className="action-secondary" aria-label="Refresh submissions"><RefreshCw size={14} /><span className="hidden sm:inline">Refresh</span></button></div>
    <div className="studio-board">{([{ status: "pending", label: "In review", color: "bg-amber-400", note: "Waiting for an admin?s review." }, { status: "rejected", label: "Needs revision", color: "bg-rose-400", note: "Feedback to help improve your material." }, { status: "approved", label: "Approved", color: "bg-emerald-500", note: "Accepted by the review team." }] as const).map(column => { const rows = result.data.filter(row => row.status === column.status); return <section key={column.status} className="studio-column"><div className="flex items-center gap-2 text-xs font-semibold"><span className={`h-2 w-2 rounded-full ${column.color}`} />{column.label}<span className="ml-auto rounded-md bg-white px-2 py-1 text-slate-500">{result.isLoading ? "?" : rows.length}</span></div><p className="mt-3 text-xs text-slate-400">{column.note}</p>{rows.slice(0, 4).map(row => <Link href="/contributor/submissions" className="studio-card" key={row.id}><span className="text-[10px] uppercase tracking-wide text-emerald-700">{resourceTypeLabel(row.resourceType)}</span><h4 className="mt-2 text-sm font-semibold">{row.title}</h4><p className="mt-2 text-xs text-slate-400">{row.courseCode} ? {row.topicName}</p>{row.rejectionReason && <p className="mt-3 line-clamp-2 border-l-2 border-rose-300 pl-2 text-xs text-rose-700">{row.rejectionReason}</p>}<p className="mt-4 text-[10px] text-slate-400">{formatRelativeTime(row.submittedAt)}</p></Link>)}{!rows.length && <p className="py-10 text-center text-xs text-slate-400">{result.isLoading ? "Loading?" : "No contributions here yet."}</p>}</section>; })}</div><Link href="/contributor/submissions" className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-800">Manage all submissions <ArrowRight size={14} /></Link>
  </div>;
}
function AdminDashboard() {
  const { user } = useAuth();
  const submissions = useDatabaseData(`admin-submissions:${user?.id}`, listSubmissionsForReview, []);
  const accounts = useDatabaseData(`admin-accounts:${user?.id}`, listPendingUsers, []);
  const stats = useDatabaseData(`admin-stats:${user?.id}`, getAdminStats, { userCount: 0, courseCount: 0, publishedResourceCount: 0, submissionCount: 0 });
  const pending = submissions.data.filter(row => row.status === "pending");
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="page-kicker mb-2">Administration / Overview</p><h2 className="page-title">Platform control center</h2><p className="mt-2 text-sm text-slate-500">Review contributions. Manage access. Keep the catalog organized.</p></div><button onClick={() => { submissions.refresh(); accounts.refresh(); stats.refresh(); }} className="action-secondary"><RefreshCw size={14} />Refresh data</button></div>
    {(submissions.error || stats.error || accounts.error) && <p role="alert" className="text-sm text-rose-600">{submissions.error ?? stats.error ?? accounts.error}</p>}
    <div className="admin-metrics">{[{ label: "Content to review", value: pending.length, href: "/admin/approvals", icon: ShieldCheck }, { label: "Accounts to approve", value: accounts.data.length, href: "/admin/user-approvals", icon: Users }, { label: "Published resources", value: stats.data.publishedResourceCount, href: "/courses", icon: BookOpen }, { label: "Active courses", value: stats.data.courseCount, href: "/admin/courses", icon: Layers }].map(({ label, value, href, icon: Icon }) => <Link key={label} href={href} className="admin-metric"><div className="flex justify-between text-slate-400"><Icon size={17} /><ArrowUpRight size={13} /></div><strong>{stats.isLoading || accounts.isLoading || submissions.isLoading ? "?" : value}</strong><span className="text-xs text-slate-500">{label}</span></Link>)}</div>
    <div className="grid items-start gap-6 xl:grid-cols-[1fr_290px]"><section className="panel"><div className="panel-heading"><div><h3>Content review queue</h3><p className="mt-1 text-xs text-slate-400">Pending submissions requiring a decision</p></div><Link href="/admin/approvals" className="text-xs font-semibold text-slate-600">View queue ?</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="px-6 py-3">Submission</th><th className="px-4 py-3">Contributor</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3"><span className="sr-only">Action</span></th></tr></thead><tbody>{pending.slice(0, 6).map(row => <tr key={row.id} className="border-t border-slate-100"><td className="px-6 py-4"><p className="font-medium">{row.title}</p><p className="mt-1 text-[11px] text-slate-400">{row.courseCode} / {resourceTypeLabel(row.resourceType)}</p></td><td className="px-4 py-4 text-xs text-slate-500">{row.contributor.name}</td><td className="px-4 py-4 text-xs text-slate-400">{formatRelativeTime(row.submittedAt)}</td><td className="px-4 py-4"><Link href="/admin/approvals" className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-semibold">Review</Link></td></tr>)}{!pending.length && <tr><td colSpan={4} className="p-10 text-center text-sm text-slate-400">{submissions.isLoading ? "Loading review queue?" : "All caught up. No content waiting for review."}</td></tr>}</tbody></table></div></section><aside className="space-y-5"><section className="panel p-5"><p className="page-kicker">Quick actions</p><div className="mt-4 space-y-3"><Link href="/admin/courses" className="action-primary w-full"><Plus size={15} />Manage courses</Link><Link href="/admin/user-approvals" className="action-secondary w-full"><Users size={15} />Manage users</Link></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-2xl font-semibold">{stats.isLoading ? "?" : stats.data.userCount}</p><p className="mt-1 text-xs text-slate-400">Active accounts on the platform</p></div></section><section className="rounded-xl border border-slate-200 p-5"><ShieldCheck size={22} className="text-slate-400" /><h3 className="mt-3 text-sm font-semibold">Review before publication</h3><p className="mt-2 text-xs leading-5 text-slate-500">Check each attachment and its course placement. Contributors? materials become available to learners after approval.</p></section></aside></div>
  </div>;
}
